image: ghcr.io/jsaady/triptasticweb:sha-cfe1937

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: triptastic-ci.holyham.dev
      paths:
      - path: /
        pathType: ImplementationSpecific

serviceAccount:
  create: false

