{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    {{- range $key, $value := .Values.postgres.pvcLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: ankane/pgvector:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.defaultPassword }}
            - name: POSTGRES_DB
              value: app
            - name: PGDATA
              value: /var/lib/postgresql/data/k8s
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

{{ if .Values.telemetry.postgres_exporter.enabled }}
---
# install the postgres exporter
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter
          env:
            - name: DATA_SOURCE_URI
              value: postgres:5432/app?sslmode=disable
            - name: DATA_SOURCE_USER
              value: postgres
            - name: DATA_SOURCE_PASS
              value: {{ .Values.postgres.defaultPassword }}
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      name: http
      port: 9187
      targetPort: 9187
{{ end }}
{{- if .Values.telemetry.prometheus_monitor.enabled -}}
---
# install a service monitor for the exporter
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: postgres-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
    - port: http
{{- end -}}
{{- end }}
