global:
  domain: argo.holyham.dev
server.insecure: "true"
configs:
  params:
    server.insecure: "true"
server:
  extraArgs:
    - "--insecure"
  ingress:
    enabled: true
    annotations:
      "tailscale.com/expose": "true"
      "kubernetes.io/ingress.class": "nginx"
      "cert-manager.io/cluster-issuer": prod-do # Use your cluster issuer name
      # Other necessary annotations can be added here
    hosts:
      - argo.holyham.dev
    tls:
      - hosts:
          - argo.holyham.dev
        secretName: argo-server-prod-do
