{{- $postgresPassword := default (randAlphaNum 64) .Values.postgresql.auth.postgresqlPassword | b64enc | quote }}

{{- if not .Values.postgresql.postgresqlPassword }}
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.auth.existingSecret) }}
   {{- if $existingSecret }}
    {{- $postgresPassword = index $existingSecret.data "postgresPassword"}}
  {{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  postgresPassword: {{ $postgresPassword }}
