{{- $postgresPassword := default (randAlphaNum 64) .Values.postgresPassword.value | b64enc | quote }}

{{- if not .Values.postgresPassword.value }}
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret) }}
   {{- if $existingSecret }}
    {{- $postgresPassword = index $existingSecret.data "postgresPassword"}}
  {{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  postgresPassword: {{ $postgresPassword }}
