# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: gitea.holyham.cloud
  IMAGE_NAME: ${{ github.repository }}
  TAG_NAME: latest
  DOMAIN_NAME: ${{ github.repository_owner }}-${{ github.ref_name }}.apps.holyham.cloud

jobs:
  build-and-push-image:
    container:
      image: catthehacker/ubuntu:act-22.04
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract env vars
        uses: ${{ github.server_url }}/jteq/actions/extract-env-vars@main

      - name: Dump ENV Vars
        run: cat ./app/app-secrets.yaml

      - name: Log in
        run: docker login ${{ env.REGISTRY }} -u ${{ gitea.actor }} -p ${{ secrets.REGISTRY_PW }}

      - name: Test
        run: echo ${{ secrets.GITEA_TOKEN }}

      - name: Build
        run: |
           docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            ${{ env.GITHUB_WORKSPACE }}

      - name: Push
        run: docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Cleanup
        run: |
          docker logout
          docker system prune -a -f

  test:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install
      run: npm ci
    - name: Run tests
      run: npm test
    # - name: Lint
    #   run: npm lint

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
